{
 "title": "Atmocube",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Air Quality #1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "voc_index", "legendFormat": "VOC Index" },
    { "expr": "nox_index", "legendFormat": "NOx Index" },
    { "expr": "co2", "legendFormat": "CO2" }
   ]
  },
  {
   "title": "Air Quality #2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tvoc", "legendFormat": "TVOC" },
    { "expr": "co", "legendFormat": "CO" },
    { "expr": "o3", "legendFormat": "O3" },
    { "expr": "ch2o", "legendFormat": "Formaldehyde" }
   ]
  },
  {
   "title": "Particle Pollution",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pm1", "legendFormat": "PM1.0" },
    { "expr": "pm25", "legendFormat": "PM2.5" },
    { "expr": "pm4", "legendFormat": "PM4" },
    { "expr": "pm10", "legendFormat": "PM10" }
   ]
  },
  {
   "title": "Indoor Index #1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature", "legendFormat": "Temperature" },
    { "expr": "humidity", "legendFormat": "Humidity" },
    { "expr": "absolute_humidity", "legendFormat": "Absolute Humidity" }
   ]
  },
  {
   "title": "Indoor Index #2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "temperature", "legendFormat": "Temperature (°C)" },
    { "expr": "humidity", "legendFormat": "Humidity (%)" }
   ]
  },
  {
   "title": "Misc.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    { "expr": "light", "legendFormat": "Light (Lx)" },
    { "expr": "noise", "legendFormat": "Noise (dB)" },
    { "expr": "pressure", "legendFormat": "Pressure (mbar)" }
   ]
  }
 ]
}